modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="ingame_biome_map"
version="${file.jarVersion}"
displayName="Ingame Biome Map Exporter"
logoFile="logo.png"
credits="Liu Dongyu"
authors="Hexagram"
description='''
With this mod, you can export the biome map of your world.
'''

[[dependencies.ingame_biome_map]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ingame_biome_map]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
