modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
modId="ingame_biome_map"
version="${file.jarVersion}"
displayName="Ingame Biome Map Exporter"
logoFile="logo.png"
credits="Liu Dongyu"
authors="Hexagram"
description='''
Use command "/exportbiomemap <radius> <scale> <player>" to export the biome map of your world in-game!
'''

[[dependencies.ingame_biome_map]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ingame_biome_map]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
